language: php

php:
  - 5.5
  - 5.6
  #- hhvm
  #- hhvm-nightly

before_script:
  - if [ $TRAVIS_PHP_VERSION = '5.6' ]; then PHPUNIT_FLAGS="--coverage-clover coverage.clover"; else PHPUNIT_FLAGS=""; fi

script:
  - ./vendor/bin/phpunit $PHPUNIT_FLAGS;
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/;
  #- if [[ $TRAVIS_PHP_VERSION != '5.3.3' && $TRAVIS_PHP_VERSION != '5.4.29' && $TRAVIS_PHP_VERSION != '5.5.13' ]]; then php -n ./vendor/bin/athletic -p ./tests/DoctrineTest/InstantiatorPerformance/ -f GroupedFormatter; fi

after_script:
  - if [ $TRAVIS_PHP_VERSION = '5.5' ]; then wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

matrix:
  allow_failures:
    - php: hhvm-nightly
