<?php
namespace wmlib\controller\Route;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-02 at 11:26:25.
 */
class StreamTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Stream
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers wmlib\controller\Route\Stream::ForFile
     * @todo   Implement testForFile().
     */
    public function testForFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
