<?php
namespace wmlib\controller;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-02 at 11:25:19.
 */
class MiddlewareTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Middleware
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers wmlib\controller\Middleware::handle
     * @todo   Implement testHandle().
     */
    public function testHandle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
