<?php
namespace wmlib\controller;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-02 at 11:22:30.
 */
class ResponseTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers wmlib\controller\Response::getSession
     * @todo   Implement testGetSession().
     */
    public function testGetSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Response::getCookies
     * @todo   Implement testGetCookies().
     */
    public function testGetCookies()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Response::setCookies
     * @todo   Implement testSetCookies().
     */
    public function testSetCookies()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Response::setSessions
     * @todo   Implement testSetSessions().
     */
    public function testSetSessions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Response::addCss
     * @todo   Implement testAddCss().
     */
    public function testAddCss()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Response::addJs
     * @todo   Implement testAddJs().
     */
    public function testAddJs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Response::setCookie
     * @todo   Implement testSetCookie().
     */
    public function testSetCookie()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Response::addError
     * @todo   Implement testAddError().
     */
    public function testAddError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Response::fetchErrors
     * @todo   Implement testFetchErrors().
     */
    public function testFetchErrors()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Response::fetchNotices
     * @todo   Implement testFetchNotices().
     */
    public function testFetchNotices()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Response::addNotice
     * @todo   Implement testAddNotice().
     */
    public function testAddNotice()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Response::getStatusCode
     * @todo   Implement testGetStatusCode().
     */
    public function testGetStatusCode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Response::getReasonPhrase
     * @todo   Implement testGetReasonPhrase().
     */
    public function testGetReasonPhrase()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Response::isSuccess
     * @todo   Implement testIsSuccess().
     */
    public function testIsSuccess()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Response::isHtml
     * @todo   Implement testIsHtml().
     */
    public function testIsHtml()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Response::isRedirect
     * @todo   Implement testIsRedirect().
     */
    public function testIsRedirect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Response::isError
     * @todo   Implement testIsError().
     */
    public function testIsError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Response::getHeaders
     * @todo   Implement testGetHeaders().
     */
    public function testGetHeaders()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Response::getRequest
     * @todo   Implement testGetRequest().
     */
    public function testGetRequest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Response::getContentType
     * @todo   Implement testGetContentType().
     */
    public function testGetContentType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Response::getHeader
     * @todo   Implement testGetHeader().
     */
    public function testGetHeader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Response::hasHeader
     * @todo   Implement testHasHeader().
     */
    public function testHasHeader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Response::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Response::getProtocolVersion
     * @todo   Implement testGetProtocolVersion().
     */
    public function testGetProtocolVersion()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Response::getBody
     * @todo   Implement testGetBody().
     */
    public function testGetBody()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Response::withStatus
     * @todo   Implement testWithStatus().
     */
    public function testWithStatus()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Response::withProtocolVersion
     * @todo   Implement testWithProtocolVersion().
     */
    public function testWithProtocolVersion()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Response::getHeaderLines
     * @todo   Implement testGetHeaderLines().
     */
    public function testGetHeaderLines()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Response::withHeader
     * @todo   Implement testWithHeader().
     */
    public function testWithHeader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Response::withAddedHeader
     * @todo   Implement testWithAddedHeader().
     */
    public function testWithAddedHeader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Response::withoutHeader
     * @todo   Implement testWithoutHeader().
     */
    public function testWithoutHeader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Response::withBody
     * @todo   Implement testWithBody().
     */
    public function testWithBody()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Response::withoutBody
     * @todo   Implement testWithoutBody().
     */
    public function testWithoutBody()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
