<?php
namespace wmlib\controller;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-02 at 11:23:58.
 */
class RouteTest extends \PHPUnit_Framework_TestCase
{


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers wmlib\controller\Route::getLogger
     * @todo   Implement testGetLogger().
     */
    public function testGetLogger()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Route::addFilter
     * @todo   Implement testAddFilter().
     */
    public function testAddFilter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Route::getDefault
     * @todo   Implement testGetDefault().
     */
    public function testGetDefault()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Route::setDefault
     * @todo   Implement testSetDefault().
     */
    public function testSetDefault()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Route::addDefault
     * @todo   Implement testAddDefault().
     */
    public function testAddDefault()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Route::addProperty
     * @todo   Implement testAddProperty().
     */
    public function testAddProperty()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Route::dispatch
     * @todo   Implement testDispatch().
     */
    public function testDispatch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Route::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Route::setLogger
     * @todo   Implement testSetLogger().
     */
    public function testSetLogger()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
