<?php
namespace wmlib\controller;

class TestStorage implements \wmlib\controller\ISessionStorage {

    /**
     * Starts the session.
     *
     * @throws \RuntimeException If something goes wrong starting the session.
     * @param $id
     * @return bool True if started.
     */
    public function start($id)
    {
        // TODO: Implement start() method.
    }

    /**
     * Save the session to storage.
     *
     * @throws \RuntimeException If something goes wrong starting the session.
     * @param $id
     * @return bool
     */
    public function save($id)
    {
        // TODO: Implement save() method.
    }

    /**
     * Remove session property
     *
     * @param $key
     * @return mixed Old value if found
     */
    public function remove($key)
    {
        // TODO: Implement remove() method.
    }

    /**
     * Set session property
     *
     * @param $key
     * @param $data
     * @return boolean
     */
    public function set($key, $data)
    {
        // TODO: Implement set() method.
    }

    /**
     * Get session property
     *
     * @param $key
     * @return mixed
     */
    public function get($key)
    {
        // TODO: Implement get() method.
    }

    /**
     * Check session property exists
     *
     * @param $key
     * @return mixed
     */
    public function has($key)
    {
        // TODO: Implement has() method.
    }
}

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-02 at 11:25:29.
 */
class SessionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Session
     */
    protected $object;
    protected $sid;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->sid = rand(0, 10000000);
        $this->object = new Session($this->sid, new TestStorage());
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers wmlib\controller\Session::getId
     * @todo   Implement testGetId().
     */
    public function testGetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Session::isStarted
     * @todo   Implement testIsStarted().
     */
    public function testIsStarted()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Session::setNamespaceStorage
     * @todo   Implement testSetNamespaceStorage().
     */
    public function testSetNamespaceStorage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Session::remove
     * @todo   Implement testRemove().
     */
    public function testRemove()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Session::set
     * @todo   Implement testSet().
     */
    public function testSet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Session::get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Session::saveAll
     * @todo   Implement testSaveAll().
     */
    public function testSaveAll()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Session::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
