<?php
namespace wmlib\controller\Filter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-02 at 11:25:44.
 */
class MiddlewareTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Middleware
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new Middleware;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers wmlib\controller\Filter\Middleware::doPreFilter
     * @todo   Implement testDoPreFilter().
     */
    public function testDoPreFilter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers wmlib\controller\Filter\Middleware::doPostFilter
     * @todo   Implement testDoPostFilter().
     */
    public function testDoPostFilter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
